# -- Time interval for the collector worker to run in Go Duration format
collectorSyncPeriod: 10s
# -- Time interval for the reloader worker to run in Go Duration format
reloaderRunPeriod: 10s

# -- Environment variables e.g. for Vault authentication
env:
  VAULT_ROLE: "reloader"
  VAULT_ADDR: "http://vault.bank-vaults.svc.cluster.local:8200"
  VAULT_NAMESPACE: "bank-vaults"
  # VAULT_TLS_SECRET: "vault-tls"
  # VAULT_TLS_SECRET_NS: "bank-vaults-infra"
  VAULT_SKIP_VERIFY: "true"
  VAULT_AUTH_METHOD: "kubernetes"
  VAULT_PATH: "kubernetes"
  # VAULT_CLIENT_TIMEOUT: "10s"
  # VAULT_IGNORE_MISSING_SECRETS: "false"