apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: vault-kv-v2-app
  namespace: app
spec:
  type: kv-v2

  # mount path
  mount: kv-v2

  # path of the secret
  path: webapp/config

  # dest k8s secret
  destination:
    name: secret-kv-v2
    create: true

  # static secret refresh interval
  refreshAfter: 10s

  # Name of the CRD to authenticate to Vault
  vaultAuthRef: static-auth
